version: '3'
services:
  strapi-v4:
    image: naskio/strapi
    restart: always
    container_name: strapi-v4
    ports:
      - '1337:1337'
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_SSL: 'false' # boolean for SSL.
    volumes:
      - app:/srv/app # create a new project in app volume
  postgres:
    restart: always
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
  app:
